// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_availability from "./routes/api/availability.ts";
import * as $index from "./routes/index.tsx";
import * as $register_index from "./routes/register/index.tsx";
import * as $reservations_index from "./routes/reservations/index.tsx";
import * as $ReservationForm from "./islands/ReservationForm.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/availability.ts": $api_availability,
    "./routes/index.tsx": $index,
    "./routes/register/index.tsx": $register_index,
    "./routes/reservations/index.tsx": $reservations_index,
  },
  islands: {
    "./islands/ReservationForm.tsx": $ReservationForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
